services:
  portfolio_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_django_portfolio_web
    container_name: tech_stack_portfolio_web
    command: python TechStackPortfolio/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - portfolio_db
      - portfolio_redis
    environment:
      DATABASE_NAME: techstackdb
      DATABASE_USER: techstackuser
      DATABASE_PASSWORD: techstackpassword
      DATABASE_HOST: 'db'
      DATABASE_PORT: 5432
      ALLOWED_HOSTS: 0.0.0.0,localhost
      REDIS_HOST: redis
      REDIS_PORT: 6379

  portfolio_db:
    image: postgres:17.0
    container_name: tech_stack_portfolio_db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: techstackdb
      POSTGRES_USER: techstackuser
      POSTGRES_PASSWORD: techstackpassword

  portfolio_redis:
    image: redis:7.4.1
    container_name: tech_stack_portfolio_redis
    ports:
      - "6390:6379"

  portfolio_prometheus:
    image: prom/prometheus
    container_name: tech_stack_portfolio_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  portfolio_grafana:
    image: grafana/grafana
    container_name: tech_stack_portfolio_grafana
    ports:
      - "3000:3000"

#  celery:
#    build:
#      context: .
#      dockerfile: dockerfiles_services/celery/Dockerfile
#    image: my_django_portfolio_celery
#    container_name: tech_stack_portfolio_celery
#    depends_on:
#      - redis
#    environment:
#      REDIS_PORT: 6379

volumes:
  postgres_data:
  prometheus_data:
