global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: "Tech_stack_monitoring"
    metrics_path: /metrics
    static_configs:
      - targets: [ "0.0.0.0:8000" ]
#  - job_name: "prometheus"
#    static_configs:
#      - targets: ["localhost:9090"]
#
#  - job_name: "django"
#    static_configs:
#      - targets: [ "web:8000" ]
#
#  - job_name: "postgres"
#    static_configs:
#      - targets: [ "postgres_exporter:9187" ]
#
#  - job_name: "redis"
#    static_configs:
#      - targets: [ "redis_exporter:9121" ]