# Generated by Django 5.1.2 on 2024-10-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinkconnect',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinkconnect',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
