# Generated by Django 5.1.2 on 2024-10-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0002_alter_sociallinkconnect_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='about_me',
            field=models.TextField(default='Missing About Me', max_length=1000),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='bio_picture',
            field=models.ImageField(blank=True, null=True, upload_to='bio_images/'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
