# Generated by Django 5.1.2 on 2024-10-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0003_mainuser_about_me_mainuser_bio_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='logo_picture',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/'),
        ),
    ]
