# Generated by Django 5.1.2 on 2024-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0004_mainuser_logo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='work_position',
            field=models.CharField(default='', max_length=50),
        ),
    ]
