# Generated by Django 5.1.2 on 2024-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0005_workexperience_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url_name_to_app', models.CharField(max_length=100)),
                ('project_picture', models.ImageField(blank=True, null=True, upload_to='project_pictures/')),
                ('technologies', models.ManyToManyField(to='main_portfolio_presentation_cv.technologies')),
            ],
        ),
        migrations.AddField(
            model_name='mainuser',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main_portfolio_presentation_cv.projects'),
        ),
    ]
