# Generated by Django 5.1.2 on 2024-11-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0006_projects_mainuser_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainUser',
            new_name='UserData',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_portfolio_presentation_cv.userdata')),
            ],
        ),
    ]
