# Generated by Django 5.1.2 on 2024-11-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portfolio_presentation_cv', '0008_alter_portfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_portfolio_presentation_cv.userdata'),
        ),
    ]
