# Generated by Django 5.1.2 on 2024-11-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
